### PR TITLE
Fill in README basics

### PR DESCRIPTION
**Pull request by ephraimg**
Still some left to do here, but added basics. Usage instructions should wait until the rest of our plan is more complete.

### CODE REVIEW

**Comment by rithnarin** [comment]
loooks okay

**Review by rithnarin — APPROVED** [review]
erhmmm

**Review by vinojg — APPROVED** [review]
Looks good

**Review by kjakpan — COMMENTED** [review]
Love the app name

**Review by vinojg — CHANGES_REQUESTED** [review]
Link for roadmap: https://docs.google.com/document/d/1J33RBBabcqbAbvGm8cRljukHOWvRAMmnkEuRl-ir0hw/edit

**Review by ephraimg — COMMENTED** [review]
thanks for fixing the link!

**Review by rithnarin — APPROVED** [review]

**Review by kjakpan — APPROVED** [review]
Excellent

**Pull request merged**
