### PR TITLE
Finish MVP navbar

### PR DESCRIPTION
**Pull request by rithnarin**
Add link to home page and search bar in navbar

### CODE REVIEW

**Review by vinojg — CHANGES_REQUESTED** [review]
Where's my sign in sign out bro?!

**Review by ephraimg — APPROVED** [review]
I think we can probably leave the sign-in button for later, once we have the basic auth-less app working. Sound OK?

**Review by ephraimg — APPROVED** [review]
Looks good for now! We should start writing our tests soon and get some fake data set up.

**Review by vinojg — APPROVED** [review]
Sounds good

**Pull request merged**
